spring:
  datasource:
    initialization-mode: always
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

bot:
  username: PddTgBot
  token: 1265644920:AAFndR3wLswvzgdPlVcKErbKgslKcIq3MT4