spring:
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/telegram_bot_pdd?useUnicode=true&serverTimezone=UTC&useSSL=false
    username: root
    password: Consensus69

bot:
  username: TestPddTgBot
  token: 1153070746:AAGfJh8HlKIQoSuTsmACRwbXBujd17SSQcg